# Generated by Django 3.0.3 on 2020-03-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20200324_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassLevels',
            new_name='Levels',
        ),
    ]
