# Generated by Django 3.0.3 on 2020-03-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_auto_20200324_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='class_name',
            field=models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.PROTECT, to='creator.Classes', to_field='class_name'),
        ),
    ]
